### ISSUE TITLE
Error method of <tbl_lazy> is for internal use only.

### ISSUE THREAD

**Issue by yichienlee2** [ohdsi-studies/EhdenAlopecia#4]
Got an error when running with R.4.2.3. There was no such error when running with R4.1.0. Below is the error message and attached is the full log. Any help is appreciated!
[study-a-thon_R_4_2_3.log](https://github.com/ohdsi-studies/EhdenAlopecia/files/13321579/study-a-thon_R_4_2_3.log)

[Error message]
Error in `covariates$"timeId"`:
! The `$` method of <tbl_lazy> is for internal use only.
ℹ Use `dplyr::pull()` to get the values in a column.

**Comment by MaximMoinat** [comment]
Thanks, that helped to find the underlying issue. It has already been reported in  https://github.com/OHDSI/CohortDiagnostics/issues/1088 and fixed https://github.com/OHDSI/CohortDiagnostics/pull/1091.

This patch has not yet been released. Could you try installing the version on the develop branch?
`remotes::install_github('OHDSI/CohortDiagnostics', ref='develop')`

**Comment by yichienlee2** [comment]
This works, thank you Maxim!
