### ISSUE TITLE
Typo in cohortsIds runTreatmentPatterns

### ISSUE THREAD

**Issue by cebarboza** [ohdsi-studies/EhdenAlopecia#7]
Should be "cohortIds" in 

https://github.com/ohdsi-studies/EhdenAlopecia/blob/1ccafed648f6a5ef5687daba83f7147cf6dce6b4/R/runTreatmentPatterns.R#L46

**Comment by rossdwilliams** [comment]
these were fixed by v1.2.0 right? @cebarboza

**Comment by cebarboza** [comment]
yes
