### ISSUE TITLE
possible error file name cohortsGenerated 

### ISSUE THREAD

**Issue by cebarboza** [ohdsi-studies/EhdenAlopecia#8]
Should the file be cohorsGenerated for the target ones? 

https://github.com/ohdsi-studies/EhdenAlopecia/blob/a8e949ca3b7db72a2abaaf910fe33a2a3651d417/R/runStudy.R#L59

**Comment by rossdwilliams** [comment]
@cebarboza this was fixed by v1.2.0 right?

**Comment by cebarboza** [comment]
yes
